version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_agent
    restart: always
    environment:
      POSTGRES_USER: csu_user
      POSTGRES_PASSWORD: eTvL2fepurbYH64JTYa7IPMOqEeIBk8Q
      POSTGRES_DB: csu
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_agent
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agentdb
      SPRING_DATASOURCE_USERNAME: agentuser
      SPRING_DATASOURCE_PASSWORD: agentpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  pg_data: