version: '3.8'

services:
  app:
    build: .
    container_name: spring_sencsu
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://sencsu94_db_user:YST1cZ8ZOp0FbHte@cluster0.qvqae2u.mongodb.net/sen-csu?retryWrites=true&w=majority
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data: